### ISSUE TITLE
df compass -bLAck

### ISSUE THREAD

**Issue by player4k** [Jelvan1/cgame_proxymod#1]
df compass
add the df_hud_cgaz 21 = compass as mdd_compass 0|1
customizable cvars for it
mdd_compass_45_rgba 1 1 0 0.5 <--- Yellow zone default 
mdd_compass_135_rgba 0 1 0 0.5 <---
mdd_compass_225_rgba
mdd_compass_315_rgba

**Comment by Jelvan1** [comment]
This is added in version v1.3.0.
